# Buildkite pipeline file
steps:
  - command: "echo hello world"
    label: ":llama:"
  - command: "cat *"
    label: ":cat:"
  - command: "env"
    label: ":cookie:"
  - command: "echo 'Deploy preview created'"
    plugins:
      - ailohq/github-status#v1.0.0
