name: Pull Request Deploy

on:
  pull_request:
    types:
      - closed
  issue_comment:
    types:
      - created   # Comment added to PR: Deploy PR
      - edited    # Commented was edited (fixing typo)

jobs:
  pr-deploy:
    name: Pull Request Nomad Deploy

    runs-on: ubuntu-latest

    # if: >-
    #   github.event_name == 'issue_comment' && github.event.issue.state == 'open' && contains(github.event.comment.body, 'do the thing')

    steps:
      - run: |
          echo '${{ toJSON(github) }}'
